# {
#     "columns":[
#         {
#             "fixed":"left",
#             "title":"排班班组",
#             "width":150,
#             "colKey":"target",
#             "ellipsis":true,
#             "panel_type":1
#         },
#         {
#             "title":"09/26 星期一",
#             "width":120,
#             "colKey":"date_2022_09_26"
#         },
#         {
#             "title":"09/27 星期二",
#             "width":120,
#             "colKey":"date_2022_09_27"
#         },
#         {
#             "title":"09/28 星期三",
#             "width":120,
#             "colKey":"date_2022_09_28"
#         },
#         {
#             "title":"09/29 星期四",
#             "width":120,
#             "colKey":"date_2022_09_29"
#         },
#         {
#             "title":"09/30 星期五",
#             "width":120,
#             "colKey":"date_2022_09_30"
#         },
#         {
#             "title":"10/01 星期六",
#             "width":120,
#             "colKey":"date_2022_10_01"
#         },
#         {
#             "title":"10/02 星期日",
#             "width":120,
#             "colKey":"date_2022_10_02"
#         },
#         {
#             "title":"10/03 星期一",
#             "width":120,
#             "colKey":"date_2022_10_03"
#         },
#         {
#             "title":"10/04 星期二",
#             "width":120,
#             "colKey":"date_2022_10_04"
#         },
#         {
#             "title":"10/05 星期三",
#             "width":120,
#             "colKey":"date_2022_10_05"
#         },
#         {
#             "title":"10/06 星期四",
#             "width":120,
#             "colKey":"date_2022_10_06"
#         },
#         {
#             "title":"10/07 星期五",
#             "width":120,
#             "colKey":"date_2022_10_07"
#         },
#         {
#             "title":"10/08 星期六",
#             "width":120,
#             "colKey":"date_2022_10_08"
#         },
#         {
#             "title":"10/09 星期日",
#             "width":120,
#             "colKey":"date_2022_10_09"
#         },
#         {
#             "title":"10/10 星期一",
#             "width":120,
#             "colKey":"date_2022_10_10"
#         },
#         {
#             "title":"10/11 星期二",
#             "width":120,
#             "colKey":"date_2022_10_11"
#         },
#         {
#             "title":"10/12 星期三",
#             "width":120,
#             "colKey":"date_2022_10_12"
#         },
#         {
#             "title":"10/13 星期四",
#             "width":120,
#             "colKey":"date_2022_10_13"
#         },
#         {
#             "title":"10/14 星期五",
#             "width":120,
#             "colKey":"date_2022_10_14"
#         },
#         {
#             "title":"10/15 星期六",
#             "width":120,
#             "colKey":"date_2022_10_15"
#         },
#         {
#             "title":"10/16 星期日",
#             "width":120,
#             "colKey":"date_2022_10_16"
#         },
#         {
#             "title":"10/17 星期一",
#             "width":120,
#             "colKey":"date_2022_10_17"
#         },
#         {
#             "title":"10/18 星期二",
#             "width":120,
#             "colKey":"date_2022_10_18"
#         },
#         {
#             "title":"10/19 星期三",
#             "width":120,
#             "colKey":"date_2022_10_19"
#         },
#         {
#             "title":"10/20 星期四",
#             "width":120,
#             "colKey":"date_2022_10_20"
#         },
#         {
#             "title":"10/21 星期五",
#             "width":120,
#             "colKey":"date_2022_10_21"
#         },
#         {
#             "title":"10/22 星期六",
#             "width":120,
#             "colKey":"date_2022_10_22"
#         },
#         {
#             "title":"10/23 星期日",
#             "width":120,
#             "colKey":"date_2022_10_23"
#         },
#         {
#             "title":"10/24 星期一",
#             "width":120,
#             "colKey":"date_2022_10_24"
#         },
#         {
#             "title":"10/25 星期二",
#             "width":120,
#             "colKey":"date_2022_10_25"
#         }
#     ],
#     "tableData":[
#         {
#             "index":"0",
#             "target":{
#                 "id":2,
#                 "date":0,
#                 "name":"测试分组-技术部"
#             },
#             "date_2022_09_26":[
#                 {
#                     "id":2,
#                     "date":26,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_09_27":[
#                 {
#                     "id":2,
#                     "date":27,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_09_28":[
#                 {
#                     "id":4,
#                     "date":28,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_09_29":[
#                 {
#                     "id":4,
#                     "date":29,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_09_30":[
#                 {
#                     "id":4,
#                     "date":30,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_01":[
#                 {
#                     "id":3,
#                     "date":1,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_02":[
#                 {
#                     "id":2,
#                     "date":2,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_03":[
#                 {
#                     "id":3,
#                     "date":3,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_04":[
#                 {
#                     "id":3,
#                     "date":4,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_05":[
#                 {
#                     "id":2,
#                     "date":5,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_06":[
#                 {
#                     "id":2,
#                     "date":6,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_07":[
#                 {
#                     "id":4,
#                     "date":7,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_08":[
#                 {
#                     "id":4,
#                     "date":8,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_09":[
#                 {
#                     "id":4,
#                     "date":9,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_10":[
#                 {
#                     "id":3,
#                     "date":10,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_11":[
#                 {
#                     "id":2,
#                     "date":11,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_12":[
#                 {
#                     "id":3,
#                     "date":12,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_13":[
#                 {
#                     "id":3,
#                     "date":13,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_14":[
#                 {
#                     "id":2,
#                     "date":14,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_15":[
#                 {
#                     "id":2,
#                     "date":15,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_16":[
#                 {
#                     "id":4,
#                     "date":16,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_17":[
#                 {
#                     "id":4,
#                     "date":17,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_18":[
#                 {
#                     "id":4,
#                     "date":18,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ],
#             "date_2022_10_19":[
#                 {
#                     "id":3,
#                     "date":19,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_20":[
#                 {
#                     "id":2,
#                     "date":20,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_21":[
#                 {
#                     "id":3,
#                     "date":21,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_22":[
#                 {
#                     "id":3,
#                     "date":22,
#                     "name":"夜班",
#                     "type":1,
#                     "styleType":2,
#                     "workTimeTypeClass":"night-work"
#                 }
#             ],
#             "date_2022_10_23":[
#                 {
#                     "id":2,
#                     "date":23,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_24":[
#                 {
#                     "id":2,
#                     "date":24,
#                     "name":"白班",
#                     "type":1,
#                     "styleType":1,
#                     "workTimeTypeClass":"day-work"
#                 }
#             ],
#             "date_2022_10_25":[
#                 {
#                     "id":4,
#                     "date":25,
#                     "name":"休息",
#                     "type":2,
#                     "styleType":3,
#                     "workTimeTypeClass":"rest"
#                 }
#             ]
#         }
#     ]
# }