import pickle
from base64 import b64decode

a = {
    "logs": "gASVPAEAAAAAAABdlCh9lCiMA3VpZJRNwQGMBHVzZXKUjAnnjovmlofnkKaUjAR0aW1llIwTMjAyMi0xMC0xOSAxMzo1Nzo0M5SMBXN0YXRllIwM5Y+R6LW35a6h5om5lHV9lCiMBWxvZ2lklIwEdXVpZJSMBFVVSUSUk5QpgZR9lIwDaW50lIoRsAXmww8dmrGhRC4RUQyJ9QBzYowDdWlklE3tAYwEdXNlcpSMCeacseWpt+WHpJSMBHRpbWWUjBMyMDIyLTEwLTE5IDEzOjU3OjQzlIwFc3RhdGWUjAblvoXlip6UjAlub2RlX2Rlc2OUjACUjBJub2RlX2FjdGl2aXR5X25hbWWUjBLlupTmlLbkvJrorqHlpI3moLiUjAlub2RlX25hbWWUjBVOb2RlX2UxcG9HZ2RKN3M4VGtZTGGUdWUu",
    "node_ready": "gASVEAEAAAAAAABdlH2UKIwKaW5wdXRfbm9kZZSMBVN0YXJ0lIwHbm9kZV9pZJSMBHV1aWSUjARVVUlElJOUKYGUfZSMA2ludJSKEbAF5sMPHZqxoUQuEVEMifUAc2KMCW5vZGVfbmFtZZSMFU5vZGVfZTFwb0dnZEo3czhUa1lMYZSMCW5vZGVfZGVzY5SMAJSMEm5vZGVfYWN0aXZpdHlfbmFtZZSMEuW6lOaUtuS8muiuoeWkjeaguJSMBHVzZXKUfZQojAJpZJRN7QGMBG5hbWWUjAnmnLHlqbflh6SUdYwIbm9kZV90cGyUfZQojApiaW5kX2ZpZWxklF2UjAtjb25zdHJhaW50c5R9lIwDdGlwlGgOdXVhLg=="}


def decode_pickle(v):
    return pickle.loads(b64decode(v))


print(decode_pickle(a["node_ready"]))

aa = [{'name': '电气系统', 'code': 'D', 'equipment_sub_system': [{'name': '高压系统', 'code': 'D1', 'equipment_type': [
    {'name': '直流电源屏', 'code': 'DCPP', 'extra_fields_info': []}, {'name': '变压器', 'code': 'T', 'extra_fields_info': []},
    {'name': '高压配电柜', 'code': 'AH', 'extra_fields_info': []}]}, {'name': '柴油发电机组系统', 'code': 'D2', 'equipment_type': [
    {'name': '发电机组', 'code': 'G', 'extra_fields_info': []},
    {'name': '发电机系统配电柜', 'code': 'GPC', 'extra_fields_info': []},
    {'name': '直流电源屏', 'code': 'DCPP', 'extra_fields_info': []},
    {'name': '发电机并机系统现场装置设备', 'code': 'GPSE', 'extra_fields_info': []},
    {'name': '供油系统现场设备', 'code': 'OSE', 'extra_fields_info': []},
    {'name': '电池开关柜', 'code': 'BAF', 'extra_fields_info': []}]}, {'name': '低压系统', 'code': 'D3', 'equipment_type': [
    {'name': '低压配电柜', 'code': 'AP', 'extra_fields_info': []}, {'name': '照明配电箱', 'code': 'AL', 'extra_fields_info': []},
    {'name': '应急照明配电箱', 'code': 'ALE', 'extra_fields_info': []},
    {'name': '消防配电箱', 'code': 'APE', 'extra_fields_info': []},
    {'name': '自动转换开关设备', 'code': 'ATS', 'extra_fields_info': []}]}, {'name': '交流UPS系统', 'code': 'D4',
                                                                     'equipment_type': [{'name': '不间断电源', 'code': 'UPS',
                                                                                         'extra_fields_info': []},
                                                                                        {'name': '蓄电池组', 'code': 'B',
                                                                                         'extra_fields_info': []},
                                                                                        {'name': '电池开关柜', 'code': 'BAF',
                                                                                         'extra_fields_info': []}]},
                                                             {'name': '直流系统', 'code': 'D5', 'equipment_type': [
                                                                 {'name': '(负48伏)直流电源系统', 'code': 'DCPS',
                                                                  'extra_fields_info': []},
                                                                 {'name': '电池开关柜', 'code': 'BAF',
                                                                  'extra_fields_info': []},
                                                                 {'name': '直流配电箱柜', 'code': 'AD',
                                                                  'extra_fields_info': []},
                                                                 {'name': '直流屏电池', 'code': 'DCPB',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '机柜供电系统', 'code': 'D6', 'equipment_type': [
                                                                 {'name': '列头柜', 'code': 'RPP',
                                                                  'extra_fields_info': []},
                                                                 {'name': '始端箱', 'code': 'PSB',
                                                                  'extra_fields_info': []},
                                                                 {'name': '插接箱', 'code': 'PCB',
                                                                  'extra_fields_info': []},
                                                                 {'name': 'PDU', 'code': 'PDU',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '机柜系统', 'code': 'D7', 'equipment_type': [
                                                                 {'name': '机柜', 'code': 'R', 'extra_fields_info': []}]},
                                                             {'name': '跨专业系统', 'code': 'D8', 'equipment_type': [
                                                                 {'name': '消防EPS', 'code': 'EPS',
                                                                  'extra_fields_info': []},
                                                                 {'name': '蓄电池组', 'code': 'B',
                                                                  'extra_fields_info': []}]}]},
      {'name': '暖通系统', 'code': 'N', 'equipment_sub_system': [{'name': '中央空调系统', 'code': 'N1', 'equipment_type': [
          {'name': '冷水主机', 'code': 'CH', 'extra_fields_info': []},
          {'name': '制冷设备控制柜', 'code': 'RCC', 'extra_fields_info': []},
          {'name': '板式换热器', 'code': 'PHE', 'extra_fields_info': []},
          {'name': '蓄冷罐', 'code': 'CST', 'extra_fields_info': []},
          {'name': '二次冷冻泵', 'code': 'CHSP', 'extra_fields_info': []},
          {'name': '一次冷冻泵', 'code': 'CHP', 'extra_fields_info': []},
          {'name': '冷却泵', 'code': 'CTP', 'extra_fields_info': []},
          {'name': '阀门控制柜', 'code': 'VCC', 'extra_fields_info': []},
          {'name': '冷却塔', 'code': 'CT', 'extra_fields_info': []},
          {'name': '软化水装置', 'code': 'SWD', 'extra_fields_info': []},
          {'name': '在线自动清洗装置', 'code': 'OCD', 'extra_fields_info': []},
          {'name': '微晶旁滤（冷却侧）', 'code': 'CMF', 'extra_fields_info': []},
          {'name': '微晶旁滤（冷冻侧）', 'code': 'RMF', 'extra_fields_info': []},
          {'name': '加药装置', 'code': 'DSD', 'extra_fields_info': []}]}, {'name': '空调系统', 'code': 'N2', 'equipment_type': [
          {'name': '精密空调', 'code': 'PAC', 'extra_fields_info': []},
          {'name': '行间空调/列间空调', 'code': 'BAC', 'extra_fields_info': []},
          {'name': '分体空调（室外机）', 'code': 'SACO', 'extra_fields_info': []},
          {'name': '分体空调（室内机）', 'code': 'SACI', 'extra_fields_info': []}]}, {'name': '恒湿系统', 'code': 'N3',
                                                                             'equipment_type': [
                                                                                 {'name': '恒湿机', 'code': 'CHU',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '加湿机', 'code': 'HU',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '除湿机', 'code': 'DHU',
                                                                                  'extra_fields_info': []}]},
                                                             {'name': '新风系统', 'code': 'N4', 'equipment_type': [
                                                                 {'name': '新风机', 'code': 'MAU',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '恒压补水系统', 'code': 'N5', 'equipment_type': [
                                                                 {'name': '加湿水（恒压补水系统）', 'code': 'HWCP',
                                                                  'extra_fields_info': []},
                                                                 {'name': '冷却水（恒压补水系统）', 'code': 'CWCP',
                                                                  'extra_fields_info': []},
                                                                 {'name': '冷冻水（恒压补水系统）', 'code': 'RWCP',
                                                                  'extra_fields_info': []},
                                                                 {'name': '生活用水（恒压补水系统）', 'code': 'LWCP',
                                                                  'extra_fields_info': []}, {'name': '水箱', 'code': 'WT',
                                                                                             'extra_fields_info': []}]},
                                                             {'name': '排水系统', 'code': 'N6', 'equipment_type': [
                                                                 {'name': '排水装置', 'code': 'DWD',
                                                                  'extra_fields_info': []}]}]},
      {'name': '弱电系统', 'code': 'R', 'equipment_sub_system': [{'name': '动力环境监控系统', 'code': 'R1', 'equipment_type': [
          {'name': '工作站', 'code': 'WS', 'extra_fields_info': []},
          {'name': '服务器', 'code': 'SE', 'extra_fields_info': []},
          {'name': '交换机', 'code': 'PBX', 'extra_fields_info': []},
          {'name': '温湿度传感器', 'code': 'THS', 'extra_fields_info': []},
          {'name': '漏水检测装置', 'code': 'WLDD', 'extra_fields_info': []},
          {'name': '氢气探测器', 'code': 'HD', 'extra_fields_info': []},
          {'name': '蓄电池内阻模块', 'code': 'BRM', 'extra_fields_info': []},
          {'name': '蓄电池电流模块', 'code': 'BCM', 'extra_fields_info': []},
          {'name': '蓄电池智能网关', 'code': 'BIG', 'extra_fields_info': []},
          {'name': '现场采集设备FAU', 'code': 'FAU', 'extra_fields_info': []},
          {'name': '弱电设备电源箱', 'code': 'AR', 'extra_fields_info': []}]}, {'name': '电力系统', 'code': 'R2',
                                                                         'equipment_type': [
                                                                             {'name': '工作站', 'code': 'WS',
                                                                              'extra_fields_info': []},
                                                                             {'name': '管理机', 'code': 'SPR',
                                                                              'extra_fields_info': []},
                                                                             {'name': '弱电设备电源箱', 'code': 'AR',
                                                                              'extra_fields_info': []}]},
                                                             {'name': '楼宇设备自控系统（BA系统）', 'code': 'R3',
                                                              'equipment_type': [{'name': '服务器', 'code': 'SE',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '工作站', 'code': 'WS',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '控制模块', 'code': 'CMOD',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '交换机', 'code': 'PBX',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '光纤收发器', 'code': 'FOT',
                                                                                  'extra_fields_info': []},
                                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                                  'extra_fields_info': []}]},
                                                             {'name': '安防系统', 'code': 'R4', 'equipment_type': [
                                                                 {'name': '工作站', 'code': 'WS', 'extra_fields_info': []},
                                                                 {'name': '服务器', 'code': 'SE', 'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '视频监控系统', 'code': 'R5', 'equipment_type': [
                                                                 {'name': '服务器', 'code': 'SE', 'extra_fields_info': []},
                                                                 {'name': '硬盘录像机', 'code': 'HDV',
                                                                  'extra_fields_info': []},
                                                                 {'name': '摄像机', 'code': 'VID',
                                                                  'extra_fields_info': []},
                                                                 {'name': '摄像机电源', 'code': 'CPS',
                                                                  'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '门禁系统', 'code': 'R6', 'equipment_type': [
                                                                 {'name': '门禁控制器', 'code': 'ADC',
                                                                  'extra_fields_info': []},
                                                                 {'name': '指纹读卡器', 'code': 'FCR',
                                                                  'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '防入侵系统', 'code': 'R7', 'equipment_type': [
                                                                 {'name': '防入侵探测器', 'code': 'IDT',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防入侵扩展模块', 'code': 'AEM',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防入侵报警主机', 'code': 'AAH',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防入侵声光报警器', 'code': 'ASA',
                                                                  'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '电子围栏系统', 'code': 'R8', 'equipment_type': [
                                                                 {'name': '高压主机', 'code': 'HPH',
                                                                  'extra_fields_info': []},
                                                                 {'name': '工作站', 'code': 'WS', 'extra_fields_info': []},
                                                                 {'name': '钢丝绳', 'code': 'SWR',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防入侵声光报警器', 'code': 'ASA',
                                                                  'extra_fields_info': []},
                                                                 {'name': '网络通讯主机', 'code': 'NCH',
                                                                  'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '矩阵系统', 'code': 'R9', 'equipment_type': [
                                                                 {'name': '矩阵', 'code': 'MAT', 'extra_fields_info': []},
                                                                 {'name': '交换机', 'code': 'PBX',
                                                                  'extra_fields_info': []},
                                                                 {'name': '显示屏', 'code': 'VIS',
                                                                  'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '灯光控制系统', 'code': 'R10', 'equipment_type': [
                                                                 {'name': '控制模块', 'code': 'CMOD',
                                                                  'extra_fields_info': []},
                                                                 {'name': '开关面板', 'code': 'SP',
                                                                  'extra_fields_info': []},
                                                                 {'name': '网关', 'code': 'GW', 'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '局域网系统（交换机）', 'code': 'R11', 'equipment_type': [
                                                                 {'name': '交换机', 'code': 'PBX',
                                                                  'extra_fields_info': []},
                                                                 {'name': '统一网关', 'code': 'UG',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防火墙设备', 'code': 'FE',
                                                                  'extra_fields_info': []},
                                                                 {'name': '弱电设备电源箱', 'code': 'AR',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '信息发布系统', 'code': 'R12', 'equipment_type': [
                                                                 {'name': '电视', 'code': 'TV', 'extra_fields_info': []},
                                                                 {'name': '后台电脑', 'code': 'BOC',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '弱电机柜系统', 'code': 'R13', 'equipment_type': [
                                                                 {'name': '机柜', 'code': 'R',
                                                                  'extra_fields_info': []}]}]},
      {'name': '消防系统', 'code': 'X', 'equipment_sub_system': [{'name': '火灾自动报警系统', 'code': 'X1', 'equipment_type': [
          {'name': '火灾报警控制器（联动型）', 'code': 'FCU', 'extra_fields_info': []},
          {'name': '消防控制室图形显示装置', 'code': 'GDD', 'extra_fields_info': []},
          {'name': '消防电话分机', 'code': 'FTE', 'extra_fields_info': []},
          {'name': '感烟探测器', 'code': 'SDE', 'extra_fields_info': []},
          {'name': '消防模块箱', 'code': 'FMB', 'extra_fields_info': []},
          {'name': '消防控制模块', 'code': 'FCM', 'extra_fields_info': []},
          {'name': '手动火灾报警按钮', 'code': 'MFA', 'extra_fields_info': []},
          {'name': '声光报警器', 'code': 'CAVA', 'extra_fields_info': []},
          {'name': '应急广播 ', 'code': 'EB', 'extra_fields_info': []}]}, {'name': '气体灭火系统', 'code': 'X2',
                                                                       'equipment_type': [
                                                                           {'name': '气体灭火控制盘 ', 'code': 'GCP',
                                                                            'extra_fields_info': []},
                                                                           {'name': '柜式气体灭火装置', 'code': 'CGD',
                                                                            'extra_fields_info': []},
                                                                           {'name': '气体喷头', 'code': 'GNO',
                                                                            'extra_fields_info': []},
                                                                           {'name': '感温探测器', 'code': 'HTE',
                                                                            'extra_fields_info': []},
                                                                           {'name': '感烟探测器', 'code': 'SDE',
                                                                            'extra_fields_info': []},
                                                                           {'name': '驱动气瓶', 'code': 'GEDC',
                                                                            'extra_fields_info': []},
                                                                           {'name': '灭火剂气瓶', 'code': 'GEFC',
                                                                            'extra_fields_info': []},
                                                                           {'name': '加压气瓶', 'code': 'PCY',
                                                                            'extra_fields_info': []},
                                                                           {'name': '气体灭火泄压口', 'code': 'GFRO',
                                                                            'extra_fields_info': []},
                                                                           {'name': '放气勿入指示灯', 'code': 'DIL',
                                                                            'extra_fields_info': []}]},
                                                             {'name': '喷淋灭火系统', 'code': 'X3', 'equipment_type': [
                                                                 {'name': '喷淋水泵 ', 'code': 'SPU',
                                                                  'extra_fields_info': []},
                                                                 {'name': '区域信号闸阀', 'code': 'ASGV',
                                                                  'extra_fields_info': []},
                                                                 {'name': '湿式报警阀组', 'code': 'WAVS',
                                                                  'extra_fields_info': []},
                                                                 {'name': '水泵接合器 ', 'code': 'SIC',
                                                                  'extra_fields_info': []},
                                                                 {'name': '未端试水装置', 'code': 'TDI',
                                                                  'extra_fields_info': []},
                                                                 {'name': '消防配电箱', 'code': 'APE',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '极早期预警系统', 'code': 'X4', 'equipment_type': [
                                                                 {'name': '极早期工作站', 'code': 'ADW',
                                                                  'extra_fields_info': []},
                                                                 {'name': '极早期火灾探测器主机 ', 'code': 'ADD',
                                                                  'extra_fields_info': []},
                                                                 {'name': '极早期火灾探测器电源', 'code': 'ADP',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '防火分隔设施系统', 'code': 'X5', 'equipment_type': [
                                                                 {'name': '防火门监控器', 'code': 'FDM',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防火卷帘门', 'code': 'FRSD',
                                                                  'extra_fields_info': []},
                                                                 {'name': '防火门', 'code': 'FID',
                                                                  'extra_fields_info': []},
                                                                 {'name': '消防配电箱', 'code': 'APE',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '电气火灾监控系统', 'code': 'X6', 'equipment_type': [
                                                                 {'name': '电气火灾监控设备', 'code': 'EFME',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '消防设备电源监控系统', 'code': 'X7', 'equipment_type': [
                                                                 {'name': '消防设备电源状态监控器', 'code': 'FEPM',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '用户信息传输装置系统', 'code': 'X8', 'equipment_type': [
                                                                 {'name': '用户信息传输装置', 'code': 'UITD',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '消火栓系统', 'code': 'X9', 'equipment_type': [
                                                                 {'name': '消防水泵', 'code': 'FPU',
                                                                  'extra_fields_info': []},
                                                                 {'name': '稳压系统', 'code': 'PSS',
                                                                  'extra_fields_info': []},
                                                                 {'name': '消火栓箱', 'code': 'HCA',
                                                                  'extra_fields_info': []},
                                                                 {'name': '消火栓按钮', 'code': 'HYB',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '消防辅助设备系统', 'code': 'X10', 'equipment_type': [
                                                                 {'name': '应急照明', 'code': 'EML',
                                                                  'extra_fields_info': []},
                                                                 {'name': '疏散指示', 'code': 'EVI',
                                                                  'extra_fields_info': []},
                                                                 {'name': '干粉灭火器', 'code': 'DPE',
                                                                  'extra_fields_info': []},
                                                                 {'name': '二氧化碳灭火器', 'code': 'CDE',
                                                                  'extra_fields_info': []},
                                                                 {'name': '安全出口灯', 'code': 'EXL',
                                                                  'extra_fields_info': []},
                                                                 {'name': '楼层显示器', 'code': 'FLI',
                                                                  'extra_fields_info': []}]},
                                                             {'name': '防/排烟系统', 'code': 'X11', 'equipment_type': [
                                                                 {'name': '排烟风机', 'code': 'SEF',
                                                                  'extra_fields_info': []},
                                                                 {'name': '排风机', 'code': 'EXF',
                                                                  'extra_fields_info': []},
                                                                 {'name': '送风机', 'code': 'FDB',
                                                                  'extra_fields_info': []},
                                                                 {'name': '消防配电箱', 'code': 'APE',
                                                                  'extra_fields_info': []}]}]}]
